development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: millionaire_development
  pool: 5
  username: root
  password: t

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: millionaire_test
  pool: 5
  username: root
  password: t

production:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: millionaire_production

  username: root
  password: t
 
