development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: millionaire_development
  pool: 5
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: millionaire_test
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: millionaire_production
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
